import React from 'react';
const authContext = React.createContext({
                                            loggedIn: true,
                                            pk: '',
                                            photo: '',
                                            username: '',
                                            displayName: '',
                                            bio: '',
                                            picks: 0,
                                            bets: 0,
                                            following: 0,
                                            followers: 0,
                                            followingList: [''],
                                            compareUsers: [''],
                                            comparePredictions: [''],
                                            checkIn: () => {},
                                            checkOut: () => {},
                                            checkInPK: (text) => {},
                                            checkInPhoto: (text) => {},
                                            checkInUsername: (text) => {},
                                            checkInDisplayName: (text) => {},
                                            checkInBio: (text) => {},
                                            checkInPicks: (number) => {},
                                            checkInBets: (number) => {},
                                            checkInFollowing: (number) => {},
                                            checkInFollowers: (number) => {},
                                            checkInFollowingList: (users) => {},
                                            checkInCompareUsers: (users) => {},
                                            checkInComparePredictions: (predictions) => {},
                                        });
export default authContext;